### ISSUE TITLE
Dedicated Linux Server Crashing on Startup

### ISSUE THREAD

**Issue by calebm02** [DominicKarma/NoxusBoss#2]
Server crashes on startup on a dedicated Linux server with just CalamityMod and SubworldLibrary loaded (bare dependencies)

[server(1).log](https://github.com/DominicKarma/NoxusBoss/files/13465528/server.1.log)
[environment-server.log](https://github.com/DominicKarma/NoxusBoss/files/13465529/environment-server.log)

**Comment by DominicKarma** [comment]
Found the problem, was due to the critters attempting to load their font data (which is ofc graphics data) server-side upon spawning.
