### ISSUE TITLE
trying to use terminus to summon nameless deity breaks my game and soft locks me

### ISSUE THREAD

**Issue by Charlotteeeeeeeeeeee** [DominicKarma/NoxusBoss#22]
Upon using terminus, everything functioned like normal, until the fact my game is permanently stuck on the "your final test begins"  screen, only way out is to alt f4 or close out, its been 20 minutes and the fight hasn't started yet, am I doing something wrong or is it actually bugged?

**Comment by PersonForSure** [comment]
I'm having the same issue
