### ISSUE TITLE
Mod calls?

### ISSUE THREAD

**Issue by WitherTaco2** [DominicKarma/NoxusBoss#27]
I don t understand how work ModCallManager (and mod call) It's so complicated there that I do not know what to enter into NoxusBoss.Call (I need to get data on whether Noxus was killed or not)

**Comment by DominicKarma** [comment]
All of it for that will route through GetBossDefeatedModCall.cs.

CallCommands indicates that "GetBossDefeated" is the identifying string used to know which call should be executed. From there it'll expect another string to specify which boss to get the downed state of. In this case, "Noxus" will suffice.

So you'd just do NoxusBoss.Call("GetBossDefeated", "Noxus");
