### ISSUE TITLE
Mod error loading

### ISSUE THREAD

**Issue by GORILLANUTS** [DominicKarma/NoxusBoss#6]
as soon as i try loading the mod in both 1.4.3 and 1.4.4, none of them work and they give an error when loading the mod. The error says something about 'accessories,wings.divineWings'. This may possibly be referring to an accessory. i'll leave a screenshot of the error just in case too.
![20231201131234_1](https://github.com/DominicKarma/NoxusBoss/assets/152600935/7b3b8a85-6922-45ee-88d9-4e85790cd5e9)

**Comment by DominicKarma** [comment]
This has recently been addressed. It will be implemented in the upcoming patch.

**Comment by GORILLANUTS** [comment]
Thank you very much for hearing me out.
