### ISSUE TITLE
Bug with the old Noxus mod

### ISSUE THREAD

**Issue by Polonisho** [DominicKarma/NoxusBoss#8]
So I went to install Wrath of the Gods to my Terraria, but it said it was already installed, so when I loaded up Terraria and checked my mods and opened the page to the Noxus mod it sent me to the Wrath of the Gods page, and I can't see any recipe for the Xeroc bossfight if there is one, any help?

**Comment by DominicKarma** [comment]
Are you on the 1.4.4 version?

**Comment by Polonisho** [comment]
No, I'm on 1.4.3

**Comment by Polonisho** [comment]
I'm right now seeing if deleting the Noxus mod then reinstalling would help

**Comment by Polonisho** [comment]
Fixed it, so I have to be on 1.4.4
